-- AlterTable
ALTER TABLE `artwork` ADD COLUMN `likes` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `comment` MODIFY `createdAt` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);
