-- AlterTable
ALTER TABLE `comment` MODIFY `createdAt` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `users` MODIFY `updatedAt` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `createdAt` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);
